### ISSUE TITLE
Questions about data.

### ISSUE THREAD

**Issue by charfole** [yangboz/shiny-guide#1]
Hello!
First of all, thank you for taking the time to fix my issue. I am also carrying out a project on Intelligent tongue diagnosis recently. Thank you for your project on GitHub sincerely, which has helped me a lot. But I have a little question. Do you have any photos of the tongue for building the automatic tongue diagnosis model? Or do you know the way to get this kind of picture? If so, can you share it with me? Thank you very much !

**Comment by yangboz** [comment]
no,I am sorry, it related to some hospital, except the data, how about the code base?
